name: xerox_student_app
description: Xerox Student Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  file_picker: ^10.0.0
  dio: ^5.9.0
  google_sign_in: ^7.2.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
